name: "Testing"

on:
  push:
    branches: [main, github-actions-test]
    paths-ignore:
      - "docs/**"
      - "README.rst"
      - "LICENSE.md"
      - ".github/workflows/docs.yml"
      - ".gitignore"

  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "README.rst"
      - ".github/workflows/docs.yml"
      - "LICENSE.md"
      - ".gitignore"

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11]
      fail-fast: false
    env:
      JUPYTER_PLATFORM_DIRS: 1

    steps:
      - uses: actions/checkout@v4
      - name: Build using Python ${{matrix.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{matrix.os}}-${{matrix.python-version}}-${{ hashFiles('pyproject.toml') }}

      - name: install dependencies [pip]
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -e .[dev,all]

      - name: unit testing for polpo [pytest]
        run: |
          xvfb-run pytest --cov-report term -m "not local" --cov=polpo ${{matrix.test-folder}}
